FROM node:22-alpine

WORKDIR /app

# npm install のためのファイルコピー
COPY package*.json ./
RUN npm install

# ソースコードのコピー
COPY . .

# Vite 用のポート
EXPOSE 5173

# 外部からのアクセスを許可するために --host を指定
CMD ["npm", "run", "dev", "--", "--host"]
